# Generated by Django 4.2.7 on 2024-01-30 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carreraJTVE',
            fields=[
                ('idCarreraJTVE', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarreraJTVE', models.CharField(max_length=150)),
                ('directorCarreraJTVE', models.CharField(max_length=150)),
                ('logoCarreraJTVE', models.FileField(blank=True, null=True, upload_to='carreraJTVE')),
                ('fechaFundacionCarreraJTVE', models.DateField()),
                ('descripcionCarreraJTVE', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cursoJTVE',
            fields=[
                ('idCursoJTVE', models.AutoField(primary_key=True, serialize=False)),
                ('nivelCursoJTVE', models.CharField(max_length=150)),
                ('descripcionCursoJTVE', models.CharField(max_length=150)),
                ('aulaCursoJTVE', models.CharField(max_length=150)),
                ('horarioCursoJTVE', models.CharField(max_length=150)),
                ('duracionCursoJTVE', models.CharField(max_length=150)),
                ('carreraJTVE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MatriculasJTVE.carrerajtve')),
            ],
        ),
        migrations.CreateModel(
            name='asignaturaJTVE',
            fields=[
                ('idAsignaturaJTVE', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAsignaturaJTVE', models.CharField(max_length=150)),
                ('creditosAsignaturaJTVE', models.CharField(max_length=150)),
                ('fechaInicioAsignaturaJTVE', models.DateField()),
                ('fechaFinalizacionAsignaturaJTVE', models.DateField()),
                ('profesorAsignaturaJTVE', models.CharField(max_length=150)),
                ('silaboAsignaturaJTVE', models.CharField(max_length=150)),
                ('descripcionAsignaturaJTVE', models.TextField()),
                ('pdfAsignaturaJTVE', models.FileField(upload_to='pdfAsignaturaJTVE/')),
                ('cursoJTVE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MatriculasJTVE.cursojtve')),
            ],
        ),
    ]
