# Generated by Django 4.2.7 on 2024-01-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatriculasJTVE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturajtve',
            name='pdfAsignaturaJTVE',
        ),
        migrations.AddField(
            model_name='asignaturajtve',
            name='tipoAsignaturaJTVE',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asignaturajtve',
            name='silaboAsignaturaJTVE',
            field=models.FileField(upload_to='pdfAsignaturaJTVE/'),
        ),
    ]
