# Generated by Django 4.2.7 on 2024-01-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatriculasJTVE', '0002_remove_asignaturajtve_pdfasignaturajtve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursojtve',
            old_name='horarioCursoJTVE',
            new_name='pisoCursoJTVE',
        ),
    ]
